### ISSUE TITLE
Why hexadecimals values are changed to 0?

### ISSUE THREAD

**Issue by XaviLC** [NordicSemiconductor/nrf-intel-hex#15] opened 2018-06-20 16:00 UTC
THe function _asHexString()_ does not map the hexadecimals values properly and they are converted to 0's?
```
let inHex = new MemoryMap();
console.log("ABCDEF123".split(""))
let inHexBytes = new Uint8Array("ABCDEF123".split(""));
inHex .set(hexAddress, inHexBytes ); 
console.log("Serial number in .hex\n"+ inHex .asHexString());
```

Gives as ouput the following, where the hex string "ABCDEF123" is not parsed at all and ABCDEF values are set to zeros...

```
[ 'A', 'B', 'C', 'D', 'E', 'F', '1', '2', '3' ]
Serial number in .hex
:020000040007F3
:09FC0000000000000000010203F5
:00000001FF
```

**Comment by IvanSanchez** [comment] 2018-06-20 21:45
This is not a bug in `asHexString`, but rather a [GIGO](https://en.wikipedia.org/wiki/Garbage_in%2C_garbage_out) caused by the way you're instantiating your `Uint8Array`. 

The `Uint8Array` constructor takes an array of **`Number`s** as its first parameter. If the elements in that array are not instances of `Number`, they will be casted into a decimal number as usual. Any letter will be casted to `NaN`, which will turn into a zero.

You can check this yourself by running the instantiation standalone:

```
> new Uint8Array("ABCDEF123".split(""));
Uint8Array(9) [ 0, 0, 0, 0, 0, 0, 1, 2, 3 ]
```

And, if you look at your output carefully, you'll see that `asHexString` is just outputting the values stored in such an Uint8Array:

```
:09FC0000000000000000010203F5
```
or
```
:09FC0000   00 00 00 00 00 00 01 02 03   F5
```


I will also call your attention over this particular line of code:

https://github.com/NordicSemiconductor/nrf-intel-hex/blob/490d9395eb4cb64bee5dbd1ac39dc55586a4de01/intel-hex.js#L201

As this is not a bug in nrf-intel-hex itself, I'm closing this.

**Closed as completed by IvanSanchez** 2018-06-20 21:45 UTC
